mainapp/urls.py
from django.urls import path,include
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('',views.Index.as_view(), name='index'),
    path('post_create',views.PostCreate.as_view(),name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(),name='post_detail'),
    path('post_update/<int:pk>',views.PostUpdate.as_view(),name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(),name='post_delete'),
    path('post_list', views.PostList.as_view(),name='post_list'),
    path('login',views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('signup_yfFDYRSfuofgud121gutD6538GUydytfn', views.SignUp.as_view(), name='signup'),
    path('a_post_create',views.APostCreate.as_view(),name='a_post_create'),
    path('profile',views.Profile.as_view(), name='profile'),
    path('p_post_create',views.ProfilePostCreate.as_view(),name='p_post_create'),
    path('p_post_detail/<int:pk>', views.ProfilePostDetail.as_view(),name='p_post_detail'),
    path('p_post_update/<int:pk>',views.PostProfileUpdate.as_view(),name='p_post_update'),
    path('p_post_delete/<int:pk>', views.PostProfileDelete.as_view(),name='p_post_delete'),
    path('search', views.Search, name='search'),
    path('p_search', views.SearchProfile, name='p_search'),
    path('p_h_search', views.SearchHightoneProfile, name='p_h_search'),
    path('p_m_search', views.SearchMiddletoneProfile, name='p_m_search'),
    path('p_l_search', views.SearchLowtoneProfile, name='p_l_search'),
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('like_list', views.LikeList.as_view(),name='like_list'),
    path('like_profile/<int:post_id>', views.Like_profile_add, name='like_profile_add'),
    path('like_profile_list', views.LikeProfileList.as_view(),name='like_profile_list'),
]

# /<int:postRecruit_id　の部分は試作段階
# path('m_p_search', views.SearchMyProfile, name='m_p_search'),

originalproject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    # author = models.ForeignKey(User, on_delete=models.PROTECT,blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = models.TextField('内容', max_length=1000)
    # category = models.ForeignKey('Category', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title

class PostRecruit(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    song = models.CharField('曲名', max_length=30)
    parts = models.TextField('募集パート', max_length=50)
    comment = models.TextField('コメント', max_length=1000)
    praTime = models.TextField('練習時間帯', max_length=300)
    # category = models.ForeignKey('Category', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.song

class PostApplication(models.Model):
    a_author = models.ForeignKey(User, verbose_name="応募したユーザー", on_delete=models.PROTECT, blank=False)
    a_parts = models.TextField('応募パート', max_length=50)
    a_comment = models.TextField('コメント', max_length=1000)
    a_created_at = models.DateTimeField(auto_now_add=True)
    a_target = models.ForeignKey(PostRecruit, on_delete=models.CASCADE, verbose_name="対象の募集")

    def __str__(self):
        return self.a_parts


class PostProfile(models.Model):
    p_author = models.ForeignKey(User, verbose_name="サークルネーム",  on_delete=models.PROTECT, blank=False)
    introduction = models.TextField('自己紹介', max_length=300)
    p_part = models.TextField('主な担当', max_length=200)
    sex = models.ForeignKey('Sex', verbose_name="性別", on_delete=models.PROTECT)
    high = models.ForeignKey('High', verbose_name="高音域", on_delete=models.PROTECT)
    middle = models.ForeignKey('Middle', verbose_name="中音域", on_delete=models.PROTECT)
    low = models.ForeignKey('Low', verbose_name="低音域", on_delete=models.PROTECT)
    freetime = models.TextField('空いている時間', max_length=300)
    p_created_at = models.DateTimeField(auto_now_add=True)
    p_update_at = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.introduction

class Like(models.Model):
    post = models.ForeignKey(PostRecruit, verbose_name="投稿", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.CASCADE)


class LikeProfile(models.Model):
    profile = models.ForeignKey(PostProfile, verbose_name="Likeされたプロフィール", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.CASCADE)


class Sex(models.Model):
    sex = models.CharField('性別', max_length=10)

    def __str__(self):
        return self.sex


class High(models.Model):
    hightone = models.CharField('高音域', max_length=10)

    def __str__(self):
        return self.hightone


class Middle(models.Model):
    middletone = models.CharField('中音域', max_length=10)

    def __str__(self):
        return self.middletone


class Low(models.Model):
    lowtone = models.CharField('低音域', max_length=10)

    def __str__(self):
        return self.lowtone

mainapp/forms.py
from re import A
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django import forms
from .models import PostApplication, PostRecruit, PostProfile
from django.contrib.auth.models import User
from .models import PostRecruit


class PostForm(forms.ModelForm):
    class Meta:
        model = PostRecruit
        fields = ('song', 'parts', 'comment', 'praTime')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PostApplicationForm(forms.ModelForm):
    class Meta:
        model = PostApplication
        fields = ('a_parts', 'a_comment')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class PostProfileForm(forms.ModelForm):
    class Meta:
        model = PostProfile
        fields = ('introduction','p_part','sex','high','middle','low','freetime')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1,max_length=30, label='', required=False)

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)


# class SearchMyProfileForm(forms.ModelForm):
#     freeword = User.username
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

mainapp/views.py
from re import template
from urllib import request
from django.shortcuts import render,resolve_url
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,CreateView,DetailView,UpdateView,DeleteView,ListView
from .models import LikeProfile, Post, PostRecruit, PostApplication, PostProfile, Like
from django.urls import reverse_lazy
from .forms import LoginForm, PostApplicationForm, PostForm, PostProfileForm, SearchForm, SignUpForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin #ログインを義務づける処理、投稿主のみ許可する処理
from django.contrib import messages
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required   #defで定義したものに関してはこれを使う

class OnlyMyPostMixin(UserPassesTestMixin): #投稿したユーザーのみが編集できるようにする処理
    raise_exception = True
    def test_func(self):
        post = PostRecruit.objects.get(id = self.kwargs['pk'])
        return post.author == self.request.user

class OnlyMyProfileMixin(UserPassesTestMixin): #投稿したユーザーのみが編集できるようにする処理
    raise_exception = True
    def test_func(self):
        post = PostProfile.objects.get(id = self.kwargs['pk'])
        return post.p_author == self.request.user

class Index(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        post_list = PostRecruit.objects.all().order_by('-update_at')
        context = {
            'post_list': post_list, 
        }
        return context

    # def confirmation_like(request,post_id):
    #     is_liked = Like.objects.filter(user = request.user, post = post_id).count()
    #     return is_liked


class PostCreate(LoginRequiredMixin, CreateView): #投稿するときの処理
    model = PostRecruit
    form_class = PostForm
    success_url = reverse_lazy('mainapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '募集を投稿しました。')
        return resolve_url('mainapp:index')

class PostDetail(DetailView): #投稿の詳細画面を定義
    model = PostRecruit

    def a_get_context_data(self, *args,**kwargs):
        a_context = super().a_get_context_data(**kwargs)
        a_post_list = PostApplication.objects.all().order_by('-a_created_at')
        a_context = {
            'a_post_list': a_post_list, 
        }
        return a_context

    #def get_context_data(self, *args, **kwargs):
    #    detail_data = Post.objects.get(id = self.kwargs['pk'])
    #    category_posts = Post.objects.filter(category = detail_data.category).order_by('-created_at')[:5]
    #    params = {
    #        'object': detail_data,
    #        'category_posts': category_posts,
    #    }
    #   return params

class PostUpdate(OnlyMyPostMixin, UpdateView): #投稿を更新する処理
    model = PostRecruit
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request,'投稿を更新しました')
        return resolve_url('mainapp:post_detail', pk=self.kwargs['pk'])

class PostDelete(OnlyMyPostMixin, DeleteView): #投稿を削除する処理
    model = PostRecruit

    def get_success_url(self):
        messages.info(self.request, '投稿を削除しました。')
        return resolve_url('mainapp:index')

class PostList(ListView):
    model = PostRecruit
    paginate_by = 5

    def get_queryset(self):
        return PostRecruit.objects.all().order_by('-update_at')

@login_required
def Like_add(request,post_id):  #お気に入りを登録する処理
    post = PostRecruit.objects.get(id = post_id)
    
    is_liked = Like.objects.filter(user = request.user, post = post_id).count()

    if is_liked > 0:  #お気に入りから削除する処理

        liked = Like.objects.filter(user = request.user, post = post_id)
        liked.delete()
        messages.info(request,'お気に入りから削除しました')

    if is_liked == 0: #お気に入りに登録する処理

        like = Like()
        like.user = request.user
        like.post = post
        like.save()
        messages.success(request,'お気に入りに追加しました')

    return redirect('mainapp:post_detail', post.id)


class LikeList(ListView):
    model = PostRecruit
    template_name = 'mainapp/like_list.html'

    def get_queryset(self):

        # a = Like.objects.all().filter(user = self.request.user)
        # return a
        # PostRecruit.objects.all().filter(song = a.post)
        return Like.objects.all().filter(user = self.request.user)

# ////////////////////////////////////////////////////////////////////////////

# @login_required
# def Like_add(request,post_id):
#     post = PostRecruit.objects.get(id = post_id)
#     is_like = Like.objects.filter(User=request.user).filter(post=post).count()
#     #unlike
#     if is_like == 1:
#         like = Like.objects.filter(User=request.user.id).filter(post=post)
#         like.delete()
#         post.count -= 1
#         post.save()

#         messages.success(request,'お気に入りから削除しました')

#         return redirect('mainapp:postRecruit_detail', post.id)
#     #like
#     if is_like == 0:
#         post.count += 1
#         post.save()
#         Like.objects.create(User=request.user, post=post)

#         messages.success(request,'お気に入りに追加しました')

#         return redirect('mainapp:postRecruit_detail', post.id)

# //////////////////////////////////////////////////////////////////////////////////

class Login(LoginView):
    form_class = LoginForm
    template_name = 'mainapp/login.html'

class Logout(LogoutView):
    template_name = 'mainapp/logout.html'

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'mainapp/signup.html'
    success_url = reverse_lazy('mainapp:index')

    def form_valid(self,form):
        user = form.save()
        login(self.request,user)
        self.object = user
        messages.info(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())



class APostCreate(LoginRequiredMixin, CreateView): #投稿するときの処理
    form_class = PostApplicationForm
    success_url = reverse_lazy('mainapp:index')

    def form_valid(self,form,post_id): 
        
        post = PostRecruit.objects.get(id = post_id)

        application = PostApplication()
        application.a_target = post
        application.save()
        form.instance.a_author_id = self.request.user.id
        return super(APostCreate, self).form_valid(form)


    def a_get_success_url(self):
        messages.success(self.request, '募集に応募しました。')
        return resolve_url('mainapp:index')


# class AIndex(TemplateView):
#     template_name = 'mainapp/postRecruit_detail.html'

#     def a_get_context_data(self, *args,**kwargs):
#         a_context = super().a_get_context_data(**kwargs)
#         a_post_list = PostApplication.objects.all().order_by('-a_created_at')
#         a_context = {
#             'a_post_list': a_post_list, 
#         }
#         return a_context



    # def A_add(request,post_id):  #お気に入りを登録する処理
    #     post = PostRecruit.objects.get(id = post_id)
        
    #     is_liked = PostApplication.objects.filter(user = request.user, post = post_id).count()
    #     if is_liked > 0:  #同じ投稿を何度もお気に入りに追加できないようにする処理
    #         messages.info(request,'すでにお気に入りに追加済みです')
    #         return redirect('mainapp:post_detail', post.id)

    #     like = PostApplication()
    #     like.user = request.user
    #     like.post = post
    #     like.save()

    #     messages.success(request,'お気に入りに追加しました')
    #     return redirect('mainapp:post_detail', post.id)

class Profile(TemplateView): #
    template_name = 'mainapp/profile.html'

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        post_list = PostProfile.objects.all().order_by('-p_update_at')
        context = {
            'post_list': post_list, 
        }
        return context

class ProfilePostCreate(LoginRequiredMixin, CreateView): #投稿するときの処理
    model = PostProfile
    form_class = PostProfileForm
    success_url = reverse_lazy('mainapp:profile')

    def form_valid(self, form):
        form.instance.p_author_id = self.request.user.id
        return super(ProfilePostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'プロフィールを投稿しました。')
        return resolve_url('mainapp:profile')

class ProfilePostDetail(DetailView): #プロフィールの詳細画面を定義
    model = PostProfile

def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = PostRecruit.objects.filter(Q(author__username = freeword)|Q(song__icontains = freeword)|Q(parts__icontains = freeword)|Q(comment__icontains = freeword)|Q(praTime__icontains = freeword))

        params = {
            'search_list': search_list,
        }

        return render (request, 'mainapp/searchRecruit.html', params)

class PostProfileUpdate(OnlyMyProfileMixin, UpdateView): #投稿を更新する処理
    model = PostProfile
    form_class = PostProfileForm

    def get_success_url(self):
        messages.info(self.request,'プロフィールを更新しました')
        return resolve_url('mainapp:p_post_detail', pk=self.kwargs['pk'])

class PostProfileDelete(OnlyMyProfileMixin, DeleteView): #投稿を削除する処理
    model = PostProfile

    def get_success_url(self):
        messages.info(self.request, 'プロフィールを削除しました。')
        return resolve_url('mainapp:profile')

@login_required
def Like_profile_add(request,post_id):  #お気に入りを登録する処理
    profile = PostProfile.objects.get(id = post_id)
    
    is_liked = LikeProfile.objects.filter(user = request.user, profile = post_id).count()

    if is_liked > 0:  #お気に入りから削除する処理

        liked = LikeProfile.objects.filter(user = request.user, profile = post_id)
        liked.delete()
        messages.info(request,'お気に入りから削除しました')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{{ request.site.siteconfig.meta_title }}</title>

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="css/mdb.min.css" />

</head>

<body>
    <!-- Start your project here-->
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid container">
                <a href="{% url 'mainapp:index' %}"><h3 class="navbar-brand">My Bands</h3></a>
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">

                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="account" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                掲示板
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="account">
                                <li>
                                    <a class="dropdown-item" href="{% url 'mainapp:index' %}">掲示板トップ</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:post_create' %}">掲示板投稿</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:post_list' %}">募集一覧</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:like_list' %}">お気に入り一覧</a>
                            </ul>
                        </li>

                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="account" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                アカウント
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="account">
                                <li>
                                    {% if request.user.is_authenticated %}
                                    <a class="dropdown-item">{{ request.user }}</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:p_post_create' %}">プロフィール投稿</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:logout' %}">ログアウト</a>
                                    {% else %}
                                    <a class="dropdown-item" href="{% url 'mainapp:login' %}">ログイン</a>
                                    {% endif %}
                                </li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                サークルメンバー
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li>
                                    <a class="dropdown-item" href="{% url 'mainapp:profile' %}">プロフィール一覧</a>
                                    <a class="dropdown-item" href="{% url 'mainapp:like_profile_list' %}">お気に入りメンバー一覧</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->
    </header>

    <main class='container'>
        {% if messages %}
        <br>
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </main>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <footer class="text-center text-white" style="background-color: #21081a;">
        <!-- Grid container -->
        <div class="container p-4"></div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2022 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>

    <!-- End your project here-->

    <!-- MDB -->
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>

    <!-- End your project here-->

    <!-- MDB -->
    <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
</body>

</html>

mainapp/templates/mainapp/postRecruit_detail.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <br>
        <div class="card">
            <h4 class="card-header">詳細</h4>
            <div class="card-body">
                <h5>曲名:</span>&nbsp;&nbsp;<strong>{{ object.song }}</strong></h5>
                <hr>
                <h5>募集パート:</span>&nbsp;&nbsp;{{ object.parts }}</h5>
                <hr>
                <h5>コメント</h5>
                <p class="card-text">{{ object.comment | linebreaksbr | urlizetrunc:15 }}</p>
                <hr>
                <h5>練習時間帯</h5>
                <p class="card-text">{{ object.praTime | linebreaksbr | urlizetrunc:15 }}</p>
                <hr>
                <h5><span>募集者:</span>&nbsp;&nbsp;{{ object.author }}</h5>
                <br>
                <a class="btn" href="{% url 'mainapp:like_add' object.id  %}" style="background-color:#FF6699; color:white;">お気に入り</a>
                <!-- {% if object.author == request.user %}
                {% else %}
                <a href="{% url 'mainapp:a_post_create' %}" class="btn btn-primary">応募</a>
                {% endif %} -->
                <hr>

                <!-- <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-dark">戻る</a> -->
                <a href="{% url 'mainapp:index' %}" class="btn btn-outline-dark">戻る</a>
                {% if object.author == request.user %}
                <a href="{% url 'mainapp:post_update' object.id %}" class="btn btn-primary">更新</a>
                <a href="{% url 'mainapp:post_delete' object.id %}" class="btn btn-outline-danger">削除</a>
                {% endif %}
            </div>
            <br>
        </div>

    </div>
    <br>
    <br>
</div>

<!-- <div class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for item in a_post_list %}
        <div class="col-md-6">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <style>
                            .small {
                                font-size: 18px;
                            }
                        </style>
                        <h3>{{ item.a_parts }}</h3>
                        <!-- <h4 class="card-title"><strong>{{ item.a_parts }}</strong></h4>
                        <p><span class="small">募集者：&nbsp;{{ item.a_author }}</span></p>
                        <hr>
                        <p class="card-text">{{ item.a_comment }}</p> -->
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">{{ item.a_created_at.date }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div> -->

{% endblock %}

mainapp/templates/mainapp/profile.html
{% extends 'mainapp/base.html' %}
{% block content %}

<br>
<br>
<div>
    <div class="p-4 shadow-4 rounded-3" style="background-color: hsl(0, 0%, 94%);">
        <h1>プロフィール一覧</h1><br>

        {% if request.user.is_authenticated %}
        <div class="d-flex align-items-center">
            <form action="{% url 'mainapp:p_search' %}" class="d-flex input-group w-auto" method="POST">
                {% csrf_token %}
                <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                    name="freeword" />
                <span class="input-group-text border-0" id="search-addon">
                    <i class="fas fa-search"></i>
                </span>
            </form>
            <div style="text-align:center">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-mdb-toggle="dropdown" aria-expanded="false">
                        音域別（得意・やや得意）
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="{% url 'mainapp:p_h_search' %}">高音域</a>
                            <a class="dropdown-item" href="{% url 'mainapp:p_m_search' %}">中音域</a>
                            <a class="dropdown-item" href="{% url 'mainapp:p_l_search' %}">低音域</a>
                        </li>
                    </ul>
                </li>
            </div>
        </div>
        {% endif %}

    </div>
</div>
<div class="row">
    <div class="col-md-9 g-4">
        {% if request.user.is_authenticated %}
        {% for item in post_list %}
        <div class="card">
            <h3 class="card-header"><strong>{{ item.p_author }}</strong></h3>
            <div class="card-body">
                <h5 class="card-title">{{ item.sex }}</h5>
                <p class="card-text"><big>{{ item.introduction|truncatechars:80 }}</big></p>
                <a href="{% url 'mainapp:p_post_detail' item.id %}" class="btn btn-primary">詳細</a>
            </div>
        </div>
        <br>
        {% endfor %}
        {% endif %}
    </div>
</div>


{% endblock %}